/** Demo buyer prefs on open seed rows so merchant chips are visible without a fresh checkout. */
export const SEED_BUYER_PREFS: Record<string, string> = {
  ord_0830: "[taksit:12] [bildirim:sms] [destek:vip] [erisim:merdiven] [kapici:3B Yılmaz] [sigorta:premium] [komsu:alma] [paketmatik:yurtici] [ambalaj:premium] [eko:geri] [hediye:Sevgilerle] [bahsis:40] [kupon:HOSGELDIN] [montaj:temel] [fatura:bireysel] [gizli:kapali] [imza:gerekli] [kirilgan:dolgu] [garanti:standart] [zil:calma] [foto:kutu] [ara:ara] [iade:30] [alici:Ayşe Yılmaz|0532 111 22 33] [firma:mng] [talimat:kapi] [saat:sabah] [gun:bugun] [hiz:express]",
  ord_0901: "[taksit:9] [bildirim:eposta] [erisim:asansor] [kapici:Kat 4] [sigorta:temel] [garanti:yil1] [destek:oncelikli] [komsu:komsuya] [paketmatik:mng] [saat:ogle] [gun:yarin] [hiz:standart] [bahsis:20] [montaj:uzman] [fatura:bireysel] [ambalaj:standart] [eko:plastiksiz] [gizli:markasiz] [imza:kimlik] [kirilgan:etiket] [zil:not] [foto:imza] [ara:whatsapp] [iade:14] [alici:Mehmet Demir] [firma:aras] [talimat:ara]",
  ord_0904: "[taksit:pesin] [bildirim:ikisi] [destek:standart] [erisim:yardim] [kapici] [sigorta:tam] [komsu:kapida] [kirilgan:cift] [montaj:tam] [paketmatik:mng] [imza:gerekli] [hediye:İyi ki doğdun] [fatura:kurumsal|Nivorius GmbH|DE123456] [ambalaj:premium] [eko:geri] [gizli:kapali] [garanti:yil2] [zil:sessiz] [foto:kapida] [ara:yok] [iade:60] [alici:Elif Kaya|0555 444 33 22] [firma:surat] [talimat:komsu] [saat:aksam] [gun:haftaici] [hiz:ayni]",
  ord_0905: "[destek:vip] [bildirim:sms] [erisim:asansor] [sigorta:temel] [komsu:komsuya] [paketmatik:ptt] [taksit:6] [odeme:kart] [firma:yurtici] [montaj:temel] [fatura:kurumsal|Demo AŞ|1234567890|Kadıköy] [ambalaj:minimal] [eko:plastiksiz] [imza:gerekmez] [garanti:yil1] [zil:calma] [foto:kutu] [ara:ara] [iade:30] [alici:Can Öztürk] [talimat:zil] [saat:sabah] [gun:cumartesi] [hiz:express]",
  ord_0906: "[taksit:3] [bildirim:eposta] [destek:oncelikli] [erisim:merdiven] [kapici:A blok] [sigorta:premium] [komsu:alma] [paketmatik:yurtici] [ambalaj:minimal] [eko:minimal] [zil:sessiz] [kupon:KARGO] [bahsis:60] [hediye] [fatura:bireysel] [gizli:markasiz] [imza:gerekli] [kirilgan:dolgu] [garanti:standart] [foto:imza] [ara:whatsapp] [iade:14] [alici:Zeynep Arslan|0544 333 22 11] [firma:mng] [talimat:kapi] [saat:ogle] [gun:bugun] [hiz:standart]",
  ord_0907: "[destek:vip] [bildirim:ikisi] [erisim:asansor] [gizli:fatura] [komsu:kapida] [paketmatik:mng] [saat:aksam] [gun:yarin] [hiz:ayni] [taksit:3] [montaj:tam] [fatura:kurumsal|Qante Demo] [ambalaj:standart] [eko:geri] [imza:gerekmez] [garanti:yil2] [zil:not] [foto:kapida] [ara:yok] [iade:60] [alici:Burak Şahin] [firma:aras] [talimat:ara]",
  ord_0908: "[taksit:12] [bildirim:sms] [destek:oncelikli] [kapici:2C Demir] [sigorta:tam] [komsu:kapida] [imza:kimlik] [erisim:yardim] [paketmatik:ptt] [kupon:QANTE10] [bahsis:40] [montaj:uzman] [fatura:bireysel] [ambalaj:premium] [eko:minimal] [gizli:fatura] [kirilgan:etiket] [garanti:yil1] [zil:sessiz] [foto:kutu] [ara:ara] [iade:30] [alici:Deniz Aydın|0533 222 11 00] [firma:yurtici] [talimat:komsu] [saat:sabah] [gun:haftaici] [hiz:express]",
  ord_0909: "[taksit:9] [bildirim:whatsapp] [destek:standart] [erisim:merdiven] [kapici:Giriş] [sigorta:premium] [komsu:komsuya] [paketmatik:yurtici] [ambalaj:premium] [eko:plastiksiz] [foto:kapida] [kupon:QANTE10] [hediye:Mutlu yıllar] [fatura:kurumsal|Atelier TR|9876543210|Beşiktaş] [gizli:kapali] [imza:kimlik] [kirilgan:cift] [garanti:yil2] [zil:calma] [ara:whatsapp] [iade:14] [alici:Selin Yıldız] [firma:surat] [talimat:zil] [saat:ogle] [gun:cumartesi] [hiz:standart]",
};
